[package]
authors = ["runner"]
edition = "2018"
name = "LearningRust"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
rand = "0.7.3"

[[bin]]
name = "learning_rust"
path = "src/main.rs"
